apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-sd-role
rules:
  - apiGroups: [ "" ]
    resources: [ "services","endpoints","pods" ]
    verbs: [ "list","get", "watch" ]
    
