{
 "title": "AMQ Broker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(artemis_consumer_count,namespace)"
   },
   {
    "name": "broker",
    "label": "broker",
    "query": "label_values(artemis_consumer_count{namespace=\"$namespace\"},broker)"
   },
   {
    "name": "address",
    "query": "label_values(artemis_consumer_count{namespace=\"$namespace\",broker=\"$broker\"},address)"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_memory_used_bytes",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{broker=\"$broker\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "jvm_memory_committed_bytes",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{broker=\"$broker\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Percentage Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (jvm_memory_used_bytes{broker=\"$broker\"} ) by (area)  / sum (jvm_memory_max_bytes{broker=\"$broker\"} ) by (area) ",
       "legendFormat": "{{ area }}"
      }
     ]
    }
   ]
  },
  { "title": "Broker General in ($namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Brokers",
   "type": "stat",
   "description": "Broker instances in selected namespace",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(artemis_address_memory_usage{namespace=\"$namespace\"})",
     "legendFormat": "brokers"
    }
   ]
  },
  {
   "title": "Connections ($broker)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(artemis_connection_count{broker=\"$broker\"})"
    }
   ]
  },
  {
   "title": "Consumers ($broker)",
   "type": "gauge",
   "description": "ID-JB-M-01 :  Sum of 'number of consumers consuming messages from this queue'",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum  (artemis_consumer_count{broker=\"$broker\"})"
    }
   ]
  },
  {
   "title": "artemis_disk_store_usage",
   "type": "gauge",
   "description": "Memory used by the disk store",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "artemis_disk_store_usage{broker=\"$broker\"} * 100",
     "legendFormat": "{{ broker }}"
    }
   ]
  },
  {
   "title": "Adress Memory Usage",
   "type": "stat",
   "description": "Bytes used by all the addresses on broker for in-memory messages",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(artemis_address_memory_usage{broker=\"$broker\"}) ",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Total Enqueue",
   "type": "stat",
   "description": "ID-JB-M-02 : number of messages routed to one or more bindings",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(artemis_routed_message_count{broker=\"$broker\"})"
    }
   ]
  },
  {
   "title": "Total Dequeue",
   "type": "stat",
   "description": "ID-JB-M-03 : Number of messages that have been acknowledge by the broker",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(artemis_messages_acknowledged{broker=\"$broker\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "messages durable",
     "type": "graph",
     "description": "number of durable messages currently in this queue (includes scheduled, paged, and in-delivery messages)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_durable_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "messages acknowledged",
     "type": "graph",
     "description": "number of messages acknowledged from this queue since it was created",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_messages_acknowledged{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_scheduled_durable_message_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_scheduled_durable_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_scheduled_message_count",
     "type": "graph",
     "description": "number of scheduled messages in this queue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_scheduled_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_delivering_durable_message_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_delivering_durable_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_delivering_message_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_delivering_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_messages_killed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_messages_killed{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "messages unrouted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_unrouted_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_message_count",
     "type": "graph",
     "description": "number of messages currently in this queue (includes scheduled, paged, and in-delivery messages)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_messages_added",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_messages_added{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "artemis_messages_expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_messages_expired{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "messages routed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (broker, address) (artemis_routed_message_count{broker=\"$broker\",address=~\"$address\"})",
       "legendFormat": "{{ address }}"
      }
     ]
    }
   ]
  },
  { "title": "Persistent Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "artemis_durable_persistent_size",
   "type": "graph",
   "description": "persistent size of durable messages currently in this queue (includes scheduled, paged, and in-delivery messages)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker, address) (artemis_durable_persistent_size{broker=\"$broker\",address=~\"$address\"})",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "artemis_persistent_size",
   "type": "graph",
   "description": "persistent size of all messages (including durable and non-durable) currently in this queue (includes scheduled, paged, and in-delivery messages)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker,address) (artemis_persistent_size{broker=\"$broker\",address=~\"$address\"})",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "artemis_delivering_durable_persistent_size",
   "type": "graph",
   "description": "persistent size of durable messages that this queue is currently delivering to its consumers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker, address) (artemis_delivering_durable_persistent_size{broker=\"$broker\",address=~\"$address\"})",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "artemis_delivering_persistent_size",
   "type": "graph",
   "description": "persistent size of messages that this queue is currently delivering to its consumers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker, address) (artemis_delivering_persistent_size{broker=\"$broker\",address=~\"$address\"})",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "artemis_scheduled_durable_persistent_size",
   "type": "graph",
   "description": "persistent size of durable scheduled messages in this queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker, address) (artemis_scheduled_durable_persistent_size{broker=\"$broker\",address=~\"$address\"})",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "artemis_scheduled_persistent_size",
   "type": "graph",
   "description": "persistent size of scheduled messages in this queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (broker, address) (artemis_scheduled_persistent_size{broker=\"$broker\",address=~\"$address\"})",
     "legendFormat": "{{ address }}"
    }
   ]
  }
 ]
}