{
 "title": "Fuse Contexts",
 "description": "Fuse Contexts",
 "tags": [
  "v1.0",
  "fuse",
  "v1.1"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(org_apache_camel_TotalProcessingTime{type=\"context\"},namespace)"
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": "label_values(org_apache_camel_TotalProcessingTime{type=\"context\",namespace=\"$namespace\"},context)"
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": "label_values(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\"},route)"
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": "label_values(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\"},processor)"
   }
  ]
 },
 "panels": [
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count by (namespace) (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"context\"})"
    }
   ]
  },
  {
   "title": "Routes in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count by (namespace) (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"routes\"})"
    }
   ]
  },
  {
   "title": "Processors in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count by (namespace) (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"processors\"})"
    }
   ]
  },
  {
   "title": "Failed in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesFailed{namespace=\"$namespace\",type=\"context\"})"
    }
   ]
  },
  {
   "title": "Completed in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"context\"})"
    }
   ]
  },
  {
   "title": "Inflight in $namespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_InflightExchanges{namespace=\"$namespace\",type=\"context\"})"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchanges  in $namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"context\"})",
       "legendFormat": "Exchanges Completed ($context)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",type=\"context\"})",
       "legendFormat": "Exchanges Failed"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesInflight{namespace=\"$namespace\",type=\"context\"})",
       "legendFormat": "Exchanges Inflight"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",type=\"context\"})",
       "legendFormat": "Exchanges Total "
      }
     ]
    },
    {
     "title": "Exchanges Context ( $context )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",context=\"$context\",type=\"context\"})",
       "legendFormat": "Exchanges Completed ($context)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",context=\"$context\",type=\"context\"})",
       "legendFormat": "Exchanges Failed ($context)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",type=\"context\"})",
       "legendFormat": "Exchanges Inflight ($context)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"context\"})",
       "legendFormat": "Exchanges Total ($context)"
      }
     ]
    },
    {
     "title": "Exchanges Route in ( $route )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=\"$route\"})",
       "legendFormat": "Exchanges Completed ($route)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=\"$route\"})",
       "legendFormat": "Exchanges Failed ($route)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=\"$route\"})",
       "legendFormat": "Exchanges Inflight ($route)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=\"$route\"})",
       "legendFormat": "Exchanges Total ($route)"
      }
     ]
    },
    {
     "title": "Exchanges Processor in ( $processor )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=\"$processor\"})",
       "legendFormat": "Exchanges Completed ($processor)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesFailed{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=\"$processor\"})",
       "legendFormat": "Exchanges Failed($processor)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=\"$processor\"})",
       "legendFormat": "Exchanges Inflight ($processor)"
      },
      {
       "expr": "sum(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=\"$processor\"})",
       "legendFormat": "Exchanges Total ($processor)"
      }
     ]
    }
   ]
  },
  { "title": "Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "ProcessingTime  in $namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",type=\"context\"}[$__interval])) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(org_apache_camel_MinProcessingTime {namespace=\"$namespace\",type=\"context\"}[$__interval])) or vector(0)",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(rate(org_apache_camel_MaxProcessingTime{namespace=\"$namespace\",type=\"context\"}[$__interval])) or vector(0)",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(rate(org_apache_camel_MeanProcessingTime{namespace=\"$namespace\",type=\"context\"}[$__interval])) or vector(0)",
     "legendFormat": "Mean"
    },
    {
     "expr": "sum(rate(org_apache_camel_LastProcessingTime{namespace=\"$namespace\",type=\"context\"}[$__interval])) or vector(0)",
     "legendFormat": "Last"
    },
    {
     "expr": "sum(rate(org_apache_camel_DeltaProcessingTime{namespace=\"$namespace\",type=\"context\"}[$__interval])) or vector(0)",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "ProcessingTime Context in ($context)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",type=\"context\",context=\"$context\"}[$__interval])) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(org_apache_camel_MinProcessingTime {namespace=\"$namespace\",type=\"context\",context=\"$context\"}[$__interval])) or vector(0)",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(rate(org_apache_camel_MaxProcessingTime{namespace=\"$namespace\",type=\"context\",context=\"$context\"}[$__interval])) or vector(0)",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(rate(org_apache_camel_MeanProcessingTime{namespace=\"$namespace\",type=\"context\",context=\"$context\"}[$__interval])) or vector(0)",
     "legendFormat": "Mean"
    },
    {
     "expr": "sum(rate(org_apache_camel_LastProcessingTime{namespace=\"$namespace\",type=\"context\",context=\"$context\"}[$__interval])) or vector(0)",
     "legendFormat": "Last"
    },
    {
     "expr": "sum(rate(org_apache_camel_DeltaProcessingTime{namespace=\"$namespace\",type=\"context\",context=\"$context\"}[$__interval])) or vector(0)",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "ProcessingTime Route in ($route)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",type=\"routes\",context=\"$context\",route=\"$route\"}[$__interval])) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(org_apache_camel_MinProcessingTime {namespace=\"$namespace\",type=\"routes\",context=\"$context\",route=\"$route\"}[$__interval])) or vector(0)",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(rate(org_apache_camel_MaxProcessingTime{namespace=\"$namespace\",type=\"routes\",context=\"$context\",route=\"$route\"}[$__interval])) or vector(0)",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(rate(org_apache_camel_MeanProcessingTime{namespace=\"$namespace\",type=\"routes\",context=\"$context\",route=\"$route\"}[$__interval])) or vector(0)",
     "legendFormat": "Mean"
    },
    {
     "expr": "sum(rate(org_apache_camel_LastProcessingTime{namespace=\"$namespace\",type=\"routes\",context=\"$context\",route=\"$route\"}[$__interval])) or vector(0)",
     "legendFormat": "Last"
    },
    {
     "expr": "sum(rate(org_apache_camel_DeltaProcessingTime{namespace=\"$namespace\",type=\"routes\",context=\"$context\",route=\"$route\"}[$__interval])) or vector(0)",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "ProcessingTime Processor in ($processor)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",type=\"processors\",context=\"$context\",processor=\"$processor\"}[$__interval])) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(org_apache_camel_MinProcessingTime {namespace=\"$namespace\",type=\"processors\",context=\"$context\",processor=\"$processor\"}[$__interval])) or vector(0)",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(rate(org_apache_camel_MaxProcessingTime{namespace=\"$namespace\",type=\"processors\",context=\"$context\",processor=\"$processor\"}[$__interval])) or vector(0)",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(rate(org_apache_camel_MeanProcessingTime{namespace=\"$namespace\",type=\"processors\",context=\"$context\",processor=\"$processor\"}[$__interval])) or vector(0)",
     "legendFormat": "Mean"
    },
    {
     "expr": "sum(rate(org_apache_camel_LastProcessingTime{namespace=\"$namespace\",type=\"processors\",context=\"$context\",processor=\"$processor\"}[$__interval])) or vector(0)",
     "legendFormat": "Last"
    },
    {
     "expr": "sum(rate(org_apache_camel_DeltaProcessingTime{namespace=\"$namespace\",type=\"processors\",context=\"$context\",processor=\"$processor\"}[$__interval])) or vector(0)",
     "legendFormat": "Delta"
    }
   ]
  }
 ]
}