apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prom-alerts-tls
  labels:
    name: prom-alerts
  name: prom-alerts
spec:
  ports:
  - name: alerts
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: prom
