apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
    service.alpha.openshift.io/serving-cert-secret-name: prom-tls
  labels:
    name: prom
  name: prom
spec:
  ports:
  - name: prometheus
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: prom

