# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
# https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    editable: false
    isDefault: true
    orgId: 1
    url: 'http://localhost:9090'
    version: 1
