apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana
  name: grafana
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
spec:
  ports:
    - name: grafana
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: grafana
