global:
  resolve_timeout: 5m
  http_config: {}
  smtp_from: admin@example.com
  smtp_hello: localhost
  smtp_smarthost: smtp.mailtrap.io:2525
  smtp_auth_username: b7b84fc3e5d118
  smtp_auth_password: <secret>
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: default
  routes:
    - receiver: Watchdog
      match:
        alertname: Watchdog
      repeat_interval: 5m
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
  - name: default
  - name: Watchdog
  - name: email
    email_configs:
      - send_resolved: false
        to: huub@redhat.com
        from: admin@example.com
        hello: localhost
        smarthost: smtp.mailtrap.io:2525
        auth_username: b7b84fc3e5d118
        auth_password: <secret>
        html: '{{ template "email.default.html" . }}'
        require_tls: false
templates: []
