apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-mon

resources:
- ../../base


#vars:
#  - name: MONITOR_PROJECT_NAME
#    objref:
#      kind: Namespace
#      name: app-mon
#      apiVersion: v1



configMapGenerator:
- files:
    - app-rules.yaml
  name: app-rules
